### ISSUE TITLE
In dynamic blocks turn `A.B()` into `new A.B()`

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-js#441]
For instance the library http://threejs.org/ uses an object namespace named `THREE` and currently the only way to instanciate a class of this lib in a browser is :
```ceylon
window.\iScene = THREE.\iScene;
dynamic scene = Scene();
```

**Comment by gavinking** [comment]
Did anyone ever open an issue against the typechecker for this?

I mean, given that `A.B()` is now the natural syntax in Ceylon for a constructor-based instantiation, I don't see any reason why this shouldn't work!

**Comment by chochos** [comment]
No I haven't opened the issue in the typechecker. But why does the typechecker need a change? `x.Y()` is already a qualified type expression

**Comment by chochos** [comment]
Oh because of what I mentioned back in November? Right. I just tested with the `hapi` example, I can fix that just now, but that's turning `a.B()` into `new a.B()`, but `A.B()` still doesn't pass the typechecker.

**Comment by gavinking** [comment]
@chochos the typechecker now accepts this.

**Comment by chochos** [comment]
The compiler already supported this, I was just waiting on typechecker support. Closing.
