### ISSUE TITLE
Wrong tuple calculation

### ISSUE THREAD

**Issue by vietj** [ceylon/ceylon-js#458]
in current ceylon.promise we allow promise conjonction: 

```
Promise<String> p1 = ...
Promise<Integer> p2 = ...
Term<String|Integer,[Integer, String]> conjonction = p1.and(p2);
```

Resolving each individual promise leads to resolve the conjonction promise.

There is a bug in JS implementation happening when resolving individual promise due to a wrong tuple calculation:

```
[ceylon-test-js] running: test.ceylon.promise::testResolveConjonction
[ceylon-test-js] ceylon.language::Exception "Cannot adapt [foo] to ceylon.language::Tuple<ceylon.language::Anything,ceylon.language::Anything,ceylon.language::Anything>"
[ceylon-test-js]     at ceylon.language::Exception
[ceylon-test-js]     at ceylon.promise::adaptValue
[ceylon-test-js]     at ceylon.promise::check$5is4p7
...
```

In this case a promise is resolved with the string _foo_ and the tuple computation should lead to the tuple `[true, 3, "foo"]` containing _foo_ and not `["foo"]`.

To reproduce this case, use the https://github.com/vietj/ceylon-sdk/ master branch.

**Comment by chochos** [comment]
This is broken again.
