### ISSUE TITLE
Native methods missing in Tuple

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-js#477]
I see this when building the language module:

```
     [java] REQUIRED NATIVE FILE MISSING FOR ceylon.language::Tuple.string => ../ceylon.language/runtime-js/Tuple/string.js, containing string
     [java] REQUIRED NATIVE FILE MISSING FOR ceylon.language::Tuple.equals => ../ceylon.language/runtime-js/Tuple/equals.js, containing equals
     [java] REQUIRED NATIVE FILE MISSING FOR ceylon.language::Tuple.hash => ../ceylon.language/runtime-js/Tuple/hash.js, containing hash
```

**Comment by FroMage** [comment]
This has to do with @gavinking adding these methods lately for the JVM I guess, and @tombentley reflecting this change in the Ceylon `Tuple` by marking them as `native`. Honestly after Gavin added them, the rest was damage control and no idea if that was the right move ;) And now you're stuck with the sticky end of the fix.

**Comment by gavinking** [comment]
I don't understand. `Tuple` doesn't specialize `equals()` and `hash`!

**Comment by FroMage** [comment]
It did, in Java (you added them), and it was thus out of sync with the Ceylon decl. @tombentley and I have been fixing this situation concurrently for days each breaking the other's fix ;)

**Comment by gavinking** [comment]
No it does not! Look again!

**Comment by tombentley** [comment]
@gavinking in ceylon/ceylon.language@9f973a5b2f01117134aca6933143e7122d452269 you added `equals()`, `hashCode()` and `toString()` to the Java version of `Tuple`. @FroMage later `@Ignore`d them, simultaneously I added them to the Ceylon declarations, because we test that the Java models match the Ceylon models. I subsequently revert my patch, but not before @chochos has seen it...

**Comment by gavinking** [comment]
But they don't actually specialize anything! They just call the superclass!

**Comment by gavinking** [comment]
Super interface rather.

**Comment by FroMage** [comment]
Well, so you're saying they should be ignored and not marked native then?

**Comment by gavinking** [comment]
Right.

**Comment by chochos** [comment]
I added those methods last Thursday. Should I remove them again?

**Comment by FroMage** [comment]
Three engineers to guess what a fourth engineer wanted to do ;)

**Comment by FroMage** [comment]
OK, made them ignored, sorry about the confusion @chochos. Now let's not refix this @tombentley OK? ;)
