### ISSUE TITLE
Error eagerly evaluating toplevel property

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-js#482]
The following fails

```ceylon
shared void run(){
    print("done.");
}

interface Foo { }
Foo noFoo = nothing;
```

with

```
$ ceylonDev compile-js && ceylonDev run-js com.example.simple
Note: Created module com.example.simple/1.0.0

/Users/jvasileff/Dropbox/Repos/ceylon/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:265
if (!cond)throw wrapexc(AssertionError(msg),loc,file);
                ^
ceylon.language::AssertionError "nothing may not be evaluated: 'false' at nothing.ceylon (11:11-11:17)"
    at AssertionError (/Users/jvasileff/Dropbox/Repos/ceylon/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:2227:6)
    at asrt$ (/Users/jvasileff/Dropbox/Repos/ceylon/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:265:25)
    at Object.getNothing (/Users/jvasileff/Dropbox/Repos/ceylon/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:3210:791)
    at $valinit$$2 (/Users/jvasileff/Desktop/js/simple/modules/com/example/simple/1.0.0/com.example.simple-1.0.0.js:27:40)
    at /Users/jvasileff/Desktop/js/simple/modules/com/example/simple/1.0.0/com.example.simple-1.0.0.js:27:66
    at /Users/jvasileff/Desktop/js/simple/modules/com/example/simple/1.0.0/com.example.simple-1.0.0.js:34:37
    at /Users/jvasileff/Desktop/js/simple/modules/com/example/simple/1.0.0/com.example.simple-1.0.0.js:1:83
    at Object.<anonymous> (/Users/jvasileff/Desktop/js/simple/modules/com/example/simple/1.0.0/com.example.simple-1.0.0.js:33:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

Based on my reading of the spec, toplevel properties should be lazily initialized:

>8.2.10. Initialization of toplevel references

>A toplevel reference has no associated frame. Instead, the lifecycle of its persistent value is associated with the loading and unloading of a module by the module runtime. **The first time a toplevel reference is accessed** following the loading of its containing module, its initializer expression is evaluated, and the resulting value is associated with the reference. This association survives until the toplevel reference is reassigned, or until the module is unloaded by the module runtime.

>Initialization of a toplevel reference may result in recursive initialization of other toplevel references. Therefore, it is possible that a cycle could occur where evaluation of a toplevel reference occurs while evaluating its initializer expression. When this occurs, an InitializationError is thrown.

**Comment by gavinking** [comment]
Hrm. I would not be averse to weakening this language if @chochos thinks it would be a pain or otherwise bad to implement that behavior in js.

**Comment by jvasileff** [comment]
I've been trying to track down a bug for a while, and I lost track if *this* issue was a contributing factor, but there *may* be related problems. For instance, is it always ok to eagerly evaluate? Or is it possible that some methods or other properties may not yet be defined?

Also - `nothing` is convenient as a placeholder. So if this behavior changes, I think ideally it should fail on Java as well, to avoid surprises.

Finally, IIRC, these module-load-time problems are very hard to diagnose if the error occurs during the loading of a dependent module. (At least in some cases, the error doesn't provide useful information, just something like:

    ceylon.language::AssertionError "Assertion failed: 'exists m = modules.find(moduleNameAndVersion[0], moduleNameAndVersion[1])' at tool.ceylon (90:15-90:89)"

But again, I don't recall all of the circumstances for that particular error.

**Comment by chochos** [comment]
Well `Foo noFoo => nothing` is the lazy version, right? I hadn't realized `Foo noFoo=nothing` should also be lazy.

**Comment by jvasileff** [comment]
My understanding is `Foo noFoo => nothing` should evaluate *every* time, whereas `Foo noFoo=nothing` initializes/evaluates once, either at module load time (currently) or the first time it is needed (as in JVM's impl.)

**Comment by gavinking** [comment]
> Well `Foo noFoo => nothing` is the lazy version, right? I hadn't realized `Foo noFoo=nothing` should also be lazy.

Well the second is "lazy", but it's also _memoized_.

**Comment by chochos** [comment]
yes it's fixed now (it was already memoized, but was being initialized eagerly)

**Comment by gavinking** [comment]
OK, great :)
