### ISSUE TITLE
Never-ending loop when iterating over members

### ISSUE THREAD

**Issue by thradec** [ceylon/ceylon-js#488]
This code runs forever ...

```
shared void run() {
    for(f in `package foo`.members<FunctionDeclaration>()) {
        print(f);
    }
}
```

**Comment by chochos** [comment]
Does it print the same member every time or does it cycle over all the members?

**Comment by chochos** [comment]
I just tested this with package `ceylon.language.meta` and it worked OK, no loop

**Comment by chochos** [comment]
Also tried this with 2 different modules I wrote p1 and p2, and it worked fine.

**Comment by thradec** [comment]
Sorry, I simplified it too much. Can you please try this code ...

```
import ceylon.language.meta.declaration {
    FunctionDeclaration
}
import ceylon.test {
    TestAnnotation,
    test
}

shared test void run() {
    for(f in `package com.acme.foo`.annotatedMembers<FunctionDeclaration, TestAnnotation>()) {
        print(f);
    }
}
```

... it print `finished` in loop

**Comment by chochos** [comment]
Still can't reproduce... iterating over a package's `annotatedMembers` works well, I tested with `SharedAnnotation` and `DefaultAnnotation` (to test for empty result) and it all worked, both with package `ceylon.language.meta` and with a simple test package I wrote.

**Comment by thradec** [comment]
Dammit, it was because I imported old version of `ceylon.test 1.1.0` with current version `1.1.1` it works (anyway thanks).
