### ISSUE TITLE
Support 1.1 and 1.1.1 binary versions for model

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-js#490]
I've bumped the binary version, so you should add code that supports loading 1.1 binaries from the current 1.1.1 like I did for the JVM backend.

See ceylon/ceylon-compiler#1975

**Comment by chochos** [comment]
Should we accept a 1.1 language module, or make an exception for that one?

**Comment by FroMage** [comment]
I'm not sure if I tested that specifically, but yes I guess so…

**Comment by chochos** [comment]
OK done. Modules compiled with 1.1.0 can be used with the 1.1.1 compiler, _except_ the language module, that one has to be 1.1.1.

**Comment by FroMage** [comment]
Thanks.

**Comment by lucaswerkmeister** [comment]
> Modules compiled with 1.1.0 can be used with the 1.1.1 compiler, except the language module, that one has to be 1.1.1.

Well it seems that 1.1.0 modules pull in the 1.1.0 language module, so we still can’t use them. See the error in #494.
