### ISSUE TITLE
Callable identity error when used in Sequence

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-js#493]
This code prints out `false`instead of `true`
```ceylon
shared void run() {
    value j = void(){};
    value m =  [j,j];
    print(m[0] == m[1]); // false instead of true
} 
```

**Comment by chochos** [comment]
Each reference to `j` is boxed separately, so they're different identities. But it can be fixed.

**Comment by chochos** [comment]
As of ceylon/ceylon.language#716 `Callable.equals` always returns false.
