### ISSUE TITLE
SDK tests hang

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-js#495]
Or take forever, but this is new, and @vietj says it should be due to changes in the JS compiler.

**Comment by chochos** [comment]
Yeah I had noticed, and I'm guessing it's related to the lookup of non-shared members or something like that because even the `ceylon.test` tests run really sloooooooow.

**Comment by chochos** [comment]
Actually the ceylon.promise and ceylon.collection tests don't take long, but the ceylon.test suite is agonizingly slow.

**Comment by chochos** [comment]
Ah, no. Found it... several stubs for the `ceylon.test` package now do stuff like `sum(0..1M)` and that takes forever in JS.

**Comment by chochos** [comment]
Introduced by @thradec in ceylon/ceylon-sdk@e971aa45fcc54a4f45d7f555d3c002e623e74393 I have no idea what he means by "runs too fast"...
