### ISSUE TITLE
Unexpected deferred anonymous object initialization 

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-js#497]
This code should print out `42` it prints out `0`
```ceylon
shared void run(){  
    variable Integer t = 0;
    object b{ t = 42;}
    print(t); // 0 : KO
}
```
This one works though :
```ceylon
shared void run(){  
    variable Integer t = 0;
    object b{ t = 42;}
    identity(b);
    print(t); // 42 : OK
}
```

**Comment by chochos** [comment]
So this isn't a bug then... the object in the first snippet is never used...

**Comment by FroMage** [comment]
Oh sorry, I was replying to a completely different issue. I'm pretty sure evaluation of an object's init section is not lazy.
