### ISSUE TITLE
annotations of anonymous classes belong to the value

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-js#506]
This code:

```ceylon
see (`class String`)
object foo {}

shared void blahblah() {
    print(annotations(`SeeAnnotation`, `class foo`));
    print(annotations(`SeeAnnotation`, `value foo`));
}
```

Should print:

```
[]
[ceylon.language.SeeAnnotation@7db82169]
```

As it does on the JVM. Currently it prints:

```
[ceylon.language::SeeAnnotation@1]
[ceylon.language::SeeAnnotation@2]
```

See https://github.com/ceylon/ceylon-spec/issues/1232.

**Comment by chochos** [comment]
So the annotations for objects only apply to the value, not the anonymous class? As you can see from the example, they're being assigned to both the class and the value...

**Comment by gavinking** [comment]
Right.
