### ISSUE TITLE
NPE compiling the SDK

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-js#507]
In line: https://github.com/ceylon/ceylon-js/blob/91387ce6a4543aa9e2126716dd05568d3dde75ab/src/main/java/com/redhat/ceylon/compiler/js/BmeGenerator.java#L65

Possibly related to changes for https://github.com/ceylon/ceylon-spec/issues/1224

```
compile-js:
   [delete] Deleting directory /Users/jvasileff/Dropbox/Repos/ceylon/ceylon-sdk/build/source-promise-js
    [mkdir] Created dir: /Users/jvasileff/Dropbox/Repos/ceylon/ceylon-sdk/build/source-promise-js
     [copy] Copying 15 files to /Users/jvasileff/Dropbox/Repos/ceylon/ceylon-sdk/build/source-promise-js/ceylon/promise
[ceylon-compile-js] Error: Errors found. Compilation stopped.
[ceylon-compile-js] Note: Created module ceylon.promise/1.1.1
[ceylon-compile-js] error encountered [GenerateJsVisitor caused an exception visiting InvocationExpression node: java.lang.NullPointerException at com.redhat.ceylon.compiler.js.BmeGenerator.hasTypeParameters(BmeGenerator.java:65)] at 90:28-90:34 of Deferred.ceylon
[ceylon-compile-js] error encountered [GenerateJsVisitor caused an exception visiting InvocationExpression node: java.lang.NullPointerException at com.redhat.ceylon.compiler.js.BmeGenerator.hasTypeParameters(BmeGenerator.java:65)] at 60:26-60:32 of Deferred.ceylon
[ceylon-compile-js] ceylon compile-js: 2 errors.
```

**Comment by lucaswerkmeister** [comment]
At [this](https://github.com/ceylon/ceylon-sdk/blob/aaa2be0bb3144f91e20f7c3a1325cf0d1bf2679c/source/ceylon/promise/Deferred.ceylon#L60) and [this](https://github.com/ceylon/ceylon-sdk/blob/aaa2be0bb3144f91e20f7c3a1325cf0d1bf2679c/source/ceylon/promise/Deferred.ceylon#L90) line in `Deferred.ceylon`.

**Comment by lucaswerkmeister** [comment]
Can also reproduced with [this code](https://gist.github.com/lucaswerkmeister/a578f38570ef1c34d98e).

**Comment by lucaswerkmeister** [comment]
Apparently the bug just occurs any time you call a parameter with functional type. However, if the parameter is declared as `Result on(T val)` instead of `Result(T) on` (i. e., an actual functional parameter), it works.

**Comment by lucaswerkmeister** [comment]
Correction: doesn’t need to be a parameter. As far as I can tell, no expression of callable type can be called *at all*.

**Comment by chochos** [comment]
this has been fixed but I didn't notice the issue until now.
