### ISSUE TITLE
Initialization error for member class inheriting from outer class

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-js#509]
This code 
```ceylon
class Foo(shared Integer i){
    shared class Bar(Integer j) extends Foo(j){
    }
}

shared void run(){
    value f = Foo(42).Bar(43);
    print(f.i);
}
```
executed, should print out `43`, but prints out `<null>`

**Comment by chochos** [comment]
Ah, the inner class is initialized before the outer class is fully initialized. Usually not a problem, except here the outer class is also the parent of the inner class.
