### ISSUE TITLE
Wrong getter is called when interface conformance is re-asserted

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-js#511]
This code produces incorrect results:

```ceylon
shared interface I {
    shared default String foo => "1";
    shared default String bar() => "1";
}

shared class C() satisfies I {
    shared actual default String foo => "2";
    shared actual default String bar() => "2";
}

shared class D() extends C() satisfies I {}

shared void testingD() {
    print(D().foo);     // prints 1
    print(D().bar());   // prints 2
}
```

Note: it's also possible to have `Interface J satisfies I {}`, and produce the error by satisfying `J`, which is happening in `ceylon.html`.

**Comment by gavinking** [comment]
Ouch!

**Comment by chochos** [comment]
I didn't quite get the `interface J` part. I defined `interface J satisfies I` and refined `foo` and `bar` in `J`, then created a class `E() satisfies J`, and got the values defined in `J`, not in `I`.

**Comment by jvasileff** [comment]
In `ceylon.html`, `J` doesn't refine `foo`, it's just that it's `J` that is satisfied by the `D`/`E` class, not `I` directly.
