### ISSUE TITLE
JS impl of Character.letter is utter nonsense

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-js#522]
Wow, the implementation of `Character.letter` for JS is totally utterly broken. We need to fix it urgently.

**Comment by gavinking** [comment]
[Here is a Java program](https://ideone.com/04llh4) that scrapes Java for the Unicode general categories of all characters, along with its output. I think we should include these ranges in the language module. [Something similar here.](http://xregexp.com/addons/unicode/unicode-base.js)

**Comment by gavinking** [comment]
While we're at it, we should scrape `java.lang.Character.isDefined()` to get a list of legal codepoints, in order to fix the impl of `Integer.character` and let me add a `Boolean codePoint` attribute to `Integer`.

**Comment by gavinking** [comment]
There is [this](https://github.com/paulmillr/unicode-categories/blob/master/index.js).

**Comment by chochos** [comment]
I can certainly port that Java program to JS. Just please, don't ever again complain about the size of the JS language module, since stuff like this will inevitably bloat it big time.

**Comment by gavinking** [comment]
:-(

**Comment by gavinking** [comment]
@chochos What I suggest we do here is separate out these lists of characters to a separate file (or even files) and load it (them) lazily when needed. WDYT?

**Comment by chochos** [comment]
That should work. Are there any other resources in the language module already, or is this going to be the first one?

**Comment by chochos** [comment]
Fixed by ceylon/ceylon.language@32dd5d22fa24a4cd5bc86489f9e94644f437b62a

**Comment by gavinking** [comment]
Excellent, thanks. How big is this file? Does it get fetched eagerly or lazily?

**Comment by quintesse** [comment]
46.7KB and I don't think source files can get lazily loaded. Maybe the info could be stored in a resource files like we do for `ceylon.locale`?

**Comment by chochos** [comment]
yeah it's a source file. The only way to lazily load this is as a separate module (basically include the original module in commonJS format).

I suppose a resource file could work, but I've no idea how to transform this into plain text and I *really* don't want to use `eval`.

**Comment by quintesse** [comment]
Couldn't we make it JSON and use `JSON.parse()`?
