### ISSUE TITLE
wrong constructor called if class has a constructor with the same name as the class

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-js#535]
For:

```ceylon
class Ec {
    shared new (String _) {
        print("In Default");
    }

    shared new Ec(String _) {
        print("In Ec.Ec");
    }
}

shared void testEc() {
    Ec("");
    Ec.Ec("");
}
```

you get:

```
In Ec.Ec
In Ec.Ec
```

**Comment by gavinking** [comment]
Confirmed.

**Comment by chochos** [comment]
Wait, so you can have a constructor with no name, *and* and constructor with the same name as the class? But the default is the one with no name, right?

**Comment by chochos** [comment]
Must be some leftover code from when the default constructor had the same name as the class.

**Comment by gavinking** [comment]
Right, exactly.

**Comment by gavinking** [comment]
Yes, that was my guess too.
