### ISSUE TITLE
Store `module` annotations in meta model

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-js#543]
Right now no annotations placed on the module descriptor are stored in the meta model, eg:

```ceylon
native("js")
module test "1.0.0" {
}
```

This is needed for https://github.com/ceylon/ceylon-spec/issues/946 and https://github.com/ceylon/ceylon-spec/issues/499

**Comment by chochos** [comment]
They are in the metamodel; available at runtime only. But the model used for compilation indeed doesn't have them.

**Comment by chochos** [comment]
Package annotations also aren't stored in the model BTW

**Comment by chochos** [comment]
OK I think this is done but please check @quintesse

**Comment by chochos** [comment]
Tests confirm this is done.
