### ISSUE TITLE
Support return statement in constructors

### ISSUE THREAD

**Issue by chochos** [ceylon/ceylon-js#548]
`return` is (will be) allowed in constructors. But it should only return from the constructor's statements, and continue executing the class initializer code.

See ceylon/ceylon-spec#1288

**Comment by chochos** [comment]
Looks like it's done.

**Comment by gavinking** [comment]
Yay! That was tricky, I bet!

**Comment by chochos** [comment]
I worked on it for a while, couldn't really figure out how to solve it, left it while I split the ClassDeclaration thing... then came back to it and kind of had an epiphany hahahah, the solution was surprisingly easy.

**Comment by gavinking** [comment]
Cool :)

**Comment by tombentley** [comment]
@chochos I guess you meant to close this?

**Comment by chochos** [comment]
Not until we can add some tests in the language module and they all pass...

**Comment by chochos** [comment]
I added some (very basic) tests in the language module. Closing.
