### ISSUE TITLE
Simplify language module compilation

### ISSUE THREAD

**Issue by chochos** [ceylon/ceylon-js#552]
The `MASTER.js` file is becoming quite messy to handle. The `Stitcher` should be able to at least identify directories there and add all their files to the compilation set; this could help eliminate a lot of manual handling of entries from the master file.

The native metamodel stuff may need some reorganizing in order to work, tho, since some native files have to be added right after certain type definitions...

**Comment by chochos** [comment]
OK this is finally done.

**Comment by gavinking** [comment]
Awesome!
