### ISSUE TITLE
implement singleton constructors

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-js#577]
Whenever you feel like it, it should be super-easy to implement support for https://github.com/ceylon/ceylon-spec/issues/1129.

**Comment by gavinking** [comment]
@chochos it looks like @tombentley has made great progress on the JVM side of this in ceylon/ceylon-compiler/issues/2176. Do you have any time to work on the JS side or are you too busy with other stuff?

**Comment by chochos** [comment]
I'lk take a look at it. It's not like those bugs are going to evolve or something. I hope...

**Comment by gavinking** [comment]
Only multiply ;-)
