### ISSUE TITLE
error for class extension of named constructor via class alias

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-js#584]
FTR I believe that it's a regression. I think that it used to work a few days ago.
This code
```ceylon
class Foo{
	shared new Foo2(){}
}
class Bar() => Foo.Foo2();
class Baz() extends Bar(){}

shared void run(){
	Baz();
}
```
executed
```
Bar.$$=Foo_Foo_Foo2.$$;
       ^
ReferenceError: Foo_Foo_Foo2 is not defined
```

**Comment by chochos** [comment]
not a regression, strictly speaking. The name for constructors was being generated wrong in some cases and fixing that caused some new issues apparently. We really do need more constructor tests, preferably in the language module. I already added some for the value constructors, so after merge I'll add some more.
