### ISSUE TITLE
Support for native header classes having members with default implementations

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-js#586]
The JVM backend now supports native header classes that can have members with default implementations like this:

```ceylon
native shared class NativeClassWithImpl(Integer x, Integer y) {
    native shared String meth() => "Method in native header class ``x`` ``y``";
}
```

You can decide to override the default implementation like this:

```ceylon
native("js") shared class NativeClassWithImpl(Integer x, Integer y) {
    native("js") shared String meth() => "Method in JS implementation class ``x`` ``y``";
}
```

or if you leave that out it will use the default implementation.

I already implemented that for toplevel methods and attributes in JS, but for classes I'm afraid it's up to you @chochos .

What I did in the JVM backend is to treat the header class as an abstract superclass and made the implementations extend it. Maybe you can do something similar?

Anyway a more extensive test is the following code:

```ceylon
shared class NativeClassWithImplBase(Integer i) {
    shared String base() => "Method in base class of native class ``i``";
}

native shared class NativeClassWithImpl(Integer x, Integer y)
        extends NativeClassWithImplBase(x) {
    native shared String meth() => "Method in native header class ``x`` ``y``";
    native shared String attr => "Attribute in native header class ``x`` ``y``";
    native shared void test2() {}
    shared String nat() => "Non-native method in native header class ``x`` ``y``";
}

native("jvm") shared class NativeClassWithImpl(Integer x, Integer y)
        extends NativeClassWithImplBase(x) {
    String jvmimpl() => "Non-shared JVM method in native implementation class";
    native("jvm") shared void test2() {
        print(base());
        print(meth());
        print(attr);
        print(nat());
        print(jvmimpl());
    }
}

native("js") shared class NativeClassWithImpl(Integer x, Integer y)
        extends NativeClassWithImplBase(x) {
    String jsimpl() => "Non-shared JS method in native implementation class";
    native("js") shared void test2() {
        print(base());
        print(meth());
        print(attr);
        print(nat());
        print(jsimpl());
    }
}

void test() {
    value x = NativeClassWithImpl(1, 2);
    x.base();
    x.test2();
    x.test2();
    x.test2();
    x.test2();
}
```

**Comment by quintesse** [comment]
Btw, the same now also has to be done for `object`s , but that should be trivial.

**Comment by chochos** [comment]
Why can't we simply use the stitching mechanism already in place?

**Comment by quintesse** [comment]
Well because this is not stitching? This is being able to write Ceylon code that's only meant for one backend or the other, not being able to include native JS code.

**Comment by chochos** [comment]
Well this particular example works. I think I'll go for objects and interfaces now, since you say you've already tackled methods and values. Then I'll add tests to the language module, to make sure everything works in both backends.

**Comment by chochos** [comment]
ah, make that _kinda_ works. Only when all header declarations are shared; if one of those is not shared, it blows up. Same for objects.

**Comment by chochos** [comment]
_sigh_ one more thing that won't work in lexical scope style...

**Comment by quintesse** [comment]
The JVM side now supports constructors as well, eg:

```ceylon
native class X {
    native new foo(Integer i) {}
    native new bar(Integer i) {}
}

native("jvm") class X {
    native("jvm") new foo(Integer i) { ... }
    // we don't specify bar() so we use the one in the header
}
```

And in the end I've gone for a stitching-style solution on the JVM side as well: instead of creating a super-class with sub-classes I just create a single class by "merging" the header and the implementation.

**Comment by quintesse** [comment]
The implementation of how I did that might even work for you @chochos , take a look here: https://github.com/ceylon/ceylon-compiler/blob/master/src/com/redhat/ceylon/compiler/java/codegen/CeylonVisitor.java#L229

It's used when visiting a `Tree.ClassBody`, If the class is a native implementation instead of just using `that.getStatements()` as it normally would to generate the body of the class it now merges the statements of both the header and the implementation (avoiding duplicates, always using the implementation in that case).

**Comment by chochos** [comment]
That's much better. I kind of do that but it's not working properly, it only works in prototype mode. By merging the classes it would also work in lexical scope mode.

What are you doing about the model? Which of the two class definitions goes to the model?

**Comment by chochos** [comment]
Is it OK if I refactor the code that merges the statements out so we can both use it?

**Comment by quintesse** [comment]
> Is it OK if I refactor the code that merges the statements out so we can both use it?
Sure!

**Comment by chochos** [comment]
@quintesse are there tests for this in the language module? I think it's done but we need to be sure at least the basic stuff works the same way in both backends

**Comment by quintesse** [comment]
Besides the couple that you added there aren't, there are full tests in the compiler project and in spec (the same tests) but not in language. Maybe there is some not-too-difficult way to use those same tests again in the language module
