### ISSUE TITLE
Update serialization

### ISSUE THREAD

**Issue by chochos** [ceylon/ceylon-js#593]
Implement @tombentley 's new serialization API in JS.

**Comment by chochos** [comment]
@tombentley what happened to s12n? I know we merged it, but the latest lib you wrote to serialize to json wasn't fully tested...

**Comment by tombentley** [comment]
I know, but it's a question of priorities. There are real-1.2 blocking bugs to fix: We can release 1.2 without having a fully tested library. It's the API which is important.

**Comment by chochos** [comment]
Well then. Closing; if any bugs arise we'll file specific issues.
