### ISSUE TITLE
Method in native header with default implementation is not found

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-js#608]
Please take a look at this branch of the language module: https://github.com/ceylon/ceylon.language/commits/native_stringbuilder

If you try to run the tests a compile error is displayed when trying to compile the JS tests:

    [ceylon-compile-js] error encountered [method or attribute does not exist: 'appendAll' in type 'StringBuilder'] at 37:20-37:28 of misc.ceylon

The `appendAll()` method *does* exist of course but is only found in the header. This is okay because it has a default implementation.

**Comment by quintesse** [comment]
Marking this "high priority" because it prevents me from merging that code and to continue work on more stuff like that.

**Comment by chochos** [comment]
Fixed by 3ef8db423c7d1711bde1d80e2569e295dd328001. Closing.
