### ISSUE TITLE
NPE in MetamodelGenerator with named object argument

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-js#612]
```ceylon
void v() {
    value v = [].follow { object head {} };
}
```
> error encountered [the 'MetamodelVisitor' caused an exception visiting a 'ObjectArgument' node: '"java.lang.NullPointerException"' at 'com.redhat.ceylon.compiler.loader.MetamodelGenerator.encodeObject([MetamodelGenerator.java:541](https://github.com/ceylon/ceylon-js/blob/adb4424c7c5fdecc47024092911c0f4a1da49047/src/main/java/com/redhat/ceylon/compiler/loader/MetamodelGenerator.java#L541))'] at 2:33-2:36 of run.ceylon

The problem is the `object head {}` (`head` is the name of `follow`’s parameter). Happens for any named argument invocation with a named object argument (originally discovered in `ceylon.ast`) if the result of the invocation is assigned to a non-toplevel value. Above example will compile if you remove `value v =` or move it outside of `void v()` (specifying an explicit type).

**Comment by quintesse** [comment]
Putting a high-prio tag on this because this affects the tests in the language module as well which can't be compiled anymore right now.

**Comment by quintesse** [comment]
@chochos I merged a temporary "fix" to make the NPE go away at least: 262446c , but please take a look at it because it's sure to be wrong

**Comment by lucaswerkmeister** [comment]
well, it’s enough to make my tests pass :)
