### ISSUE TITLE
inconsistency in tuple types

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-js#614]
Try running this code:

```ceylon
shared void testTupleType() {
    Object str = "hello";
    value tuple = [str];
    print (type(tuple));
    print (tuple is [String]);
    print (tuple is List<String> );
}
```

On the JVM, I get:

```
ceylon.language::Tuple<ceylon.language::String,ceylon.language::String,ceylon.language::empty>
true
true
```

On JS, I get:

```
[ceylon.language::Object]
true
false
```

Which is self-inconsistent.

**Comment by chochos** [comment]
so `Tuple` in JVM determines its types from its contents, rather than from type info at compile time? Is that the expected behavior, or should I just copy (when possible) the behavior of the jvm backend?

**Comment by jvasileff** [comment]
@gavinking Wouldn't changing JS to match JVM's disregard for static types just encourage "bad" code that relies on this unusual and unspecified behavior?

**Comment by quintesse** [comment]
This was done on purpose and was suggested by @gavinking himself. The justification being that the result will at least be "just as good" as the expected answer (it can only be more specific). So I guess it would be okay to do the same for JS.

**Comment by jvasileff** [comment]
It's sound, but if I start writing code that relies on the reified type being the same as the runtime type, then my code will be technically incorrect, and will break if this unspecified behavior ever changes.

So, if it's 1) extra work, and 2) unspecified, should it really be done?

**Comment by quintesse** [comment]
ad 1) I don't think it's that much extra work, and in fact I think the JS backend *should* probably do the same because the type info for tuples tends to be *very* expensive storage-wise.

ad 2) well that seems easy enough, just tell @gavinking to spec it ;)

**Comment by jvasileff** [comment]
Ok, yeah, doing it for performance makes sense to me if that will help. My objection was doing this for the sake of sameness. But I still think it's unusual behavior :stuck_out_tongue_winking_eye:

**Comment by quintesse** [comment]
I don't know if it's unusual, isn't a bit like having code that deals with `HashMap` but when you print its name it says `InternalHashMapImpl`?

**Comment by jvasileff** [comment]
Well, the problem I have with it is that it is *convenient* and seemingly nice to have, but is something that shouldn't be used, because it's not reliable. So, all else being equal, I think the change makes Ceylon *provably* worse, because the only programs that it makes work that otherwise wouldn't, are programs that are incorrectly written. (i.e. `tuple is [String]` is *not* the correct way to check the runtime type of the first element.)

A second problem is that for someone trying to learn and understand reified generics, it is confusing.

I guess the analogy with `InternalHashMapImpl` would be if `InternalHashMapImpl` had some useful methods. But it's generally considered an anti-pattern to cast to internal types to leverage their capabilities. But at least in the `InternalHashMapImpl` case, the abuse would be obvious.

Please note, though, my "all else being equal" caveat!

**Comment by chochos** [comment]
A side effect of this is that the `Element` type parameter in that Tuple would be `String` instead of `Object` (as well as `First` obviously). And now that I'm working on this, I have to disregard type info for the Tuple in two places: When the Tuple is created, and inside the special case of `type()` for a Tuple, where I was using the function's type argument; now I have to use the Tuple's type arguments instead (no biggie, I think)

**Comment by quintesse** [comment]
> because the only programs that it makes work that otherwise wouldn't, are programs that are incorrectly written.

But isn't that exactly what makes it okay? The *only* way you could ever find out the difference between the "fake" information and the correct one is to write an "incorrect" program. All correct programs will not notice the difference.

> A second problem is that for someone trying to learn and understand reified generics, it is confusing.

I don't see that at all, how would they get confused?

**Comment by jvasileff** [comment]
It's better for incorrect programs to fail fast, so you can be made aware they are incorrect. But I agree, what makes this ok is that it never makes correct programs fail.

The confusion with understanding reified generics is that in *every* other case, the static type is used. So beginners shouldn't experiment with Tuples. And I know that *many* developers have trouble with static vs. dynamic/compile type vs. runtime.

**Comment by quintesse** [comment]
But I still have trouble understanding where those beginners would get into trouble just by playing around with reified generics and Tuples. What would you see a beginner do that would throw them off or confuse them?

**Comment by jvasileff** [comment]
Normally the results for the code in the issue description would be `false`, `false`. But, experimenting with just `Tuple`s on the JVM, I'd erroneously conclude that reified generics indicate runtime information about the contents. Or perhaps that type inference happens at runtime. This doesn't even make sense for a bunch of reasons, but as a beginner, I'd be confused, and especially so when trying to use `Tuple`s to learn about variance!

So I'd recommend someone experiment with `Array`s or something, but not `Tuple`s:

```ceylon
    print((Array<Object>{""}) is List<String>);
    print((Array{"" of Object}) is List<String>);

    print((Tuple<Object,Object,[]>("",[])) is List<String>);
    print((Tuple("" of Object,[])) is List<String>);
```

**Comment by gavinking** [comment]
The JS backend should do this iff it improves performance.

**Comment by chochos** [comment]
@gavinking it improves compiler performance, but it might actually be a bit slower at runtime, since it has to determine the type of each element when the Tuple is created.

**Comment by quintesse** [comment]
@chochos slower at runtime *if* you need to use the reified type, right? And only the first time if you store the result.

**Comment by quintesse** [comment]
Ok @jvasileff I understand, although those are perhaps not completely "beginner" examples, but one certainly has to be aware of what's happening there, yes.

**Comment by chochos** [comment]
@quintesse no, slower at runtime whenever you create a tuple with `[a,b,c]` syntax (and some other cases where a tuple is created). Currently the element types are passed as an argument to the function that creates the tuple; I'm removing that and letting the function calculate the element types instead. It's two function calls, an access to a JS object, and adding the type arguments for the type if it has any.
