### ISSUE TITLE
Error: Unexpected token ILLEGAL for class in anonymous object

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-js#617]
```ceylon
Basic o = object {
    class C() {}
};
```

> /run/media/lucas/Windows/Users/Lucas/workspace/tmp/modules/tmp/1.0.0/tmp-1.0.0.js:19
```js
function C$anonymous#0($4$){
                    ^
```
SyntaxError: Unexpected token ILLEGAL

This bug was originally exposed by @gavinking, as his implementation of `Iterable.distinct` contains an anonymous object with an inner `Entry` class. As a result, the language module currently can’t be loaded.

**Comment by chochos** [comment]
Forgot to mention the issue in the commits, but this was fixed by @5be006f60a7741e467d38840a659167779281417
