### ISSUE TITLE
no error when I satisfy a Java interface in the IDE

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-js#630]
At `JsCompiler.java:229` we have some code that adds an error if I try to call a Java declaration from some code that is being compiled by the JS backend.

We have nothing like that for a class that satisfies a Java interface, so the JS compiler happily compiles such a class in the IDE.

**Comment by chochos** [comment]
And this is only possible from the IDE? I tried to compile something like this and I can't from CLI:

```ceylon
import java.lang { Serializable, JObj=Object }

shared class Clase() extends JObj() {}

shared interface Interfaz satisfies Serializable {}
```

**Comment by gavinking** [comment]
Right, of course. On the CLI obviously there's no model loader for Java!

**Comment by chochos** [comment]
this should do it. But perhaps a duplicate error will now show up when trying to extend a Java class

**Comment by gavinking** [comment]
Looks good to me! Thanks.
