### ISSUE TITLE
Collect stack trace with Error.stack

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-js#632]
`Throwable` [uses `.caller` to collect the stack trace](https://github.com/ceylon/ceylon.language/blob/32cb209ac27dfe559df992bb9757d5a3e8f7b798/runtime-js/Throwable_cons_before.js#L4). However, use of `.caller` is [explicitly prohibited](http://www.ecma-international.org/ecma-262/5.1/#sec-13.2) in ES5 strict mode; thus, attempting to create a `Throwable` in strict mode fails with a `TypeError`. (This was the cause of ceylon/ceylon-web-ide-backend#75.)

All modern engines also offer another way to get a stack trace: [`Error().stack`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Stack). This is, unfortunately, also unspecified, but available even in strict mode. Therefore, I think `Throwable` should try to use that first, and only fall back to `.caller` if `Error().stack` isn’t available.

**Comment by quintesse** [comment]
I think this is actually an issue for the language module. But anyway I've added some try-catches around the `.caller` bits so strict mode will at least not cause any problems anymore.

**Comment by lucaswerkmeister** [comment]
Well, if an empty stacktrace isn’t a problem, sure :P

(And yeah, this probably belongs in ceylon.language, didn’t think about that. Sorry.)

**Comment by chochos** [comment]
I've wondered about this before. But this stack won't have any refs to Ceylon code, just the generated code (not like we show source locations anyway). I guess we could make `Throwable` extend `Error`, or maybe just use `Error.stack` inside its constructor... or maybe the `throwexc` function from the language module could use that.

**Comment by lucaswerkmeister** [comment]
> or maybe just use `Error.stack` inside its constructor

yes, that’s what I meant – check `Error().stack` (stack of new error) in the `Throwable` constructor, where we currently walk `.caller`.

**Comment by chochos** [comment]
Fixed by ceylon/ceylon.language@8a010e162aa014850cc2099c529ccfe14f596707

**Comment by lucaswerkmeister** [comment]
Thanks!
