### ISSUE TITLE
runtime error in web IDE

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-js#633]
When running one of the examples in the web IDE I encountered this problem:

```ceylon
Object onums = 1..10;
assert (onums is Character);
```

Causes:

```
Runtime error:
--- TypeError: Cannot read property 'equals' of undefined
```

Does not occur running on node, FTR.

**Comment by chochos** [comment]
Strange. And stranger still, `assert(onums is Range<Integer>)` doesn't cause anything, so apparently this is only when the assertion fails. Probably something to do with the thrown error.

**Comment by chochos** [comment]
OK so this seems related to #632 so I might have to implement that to fix this one...

**Comment by quintesse** [comment]
Updated the Web IDE and it has solved the problem. Thx @chochos !
