### ISSUE TITLE
dupe errors calling Java declaration from JS

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-js#637]
I have this code in the IDE:

```ceylon
class Ceylon() {
    Java();
}
```

On the illegal call to `Java()`, I get this message duplicated 6 times:

    Cannot call Java declarations in Javascript

**Comment by gavinking** [comment]
@chochos wait, i may have already fixed it.

**Comment by gavinking** [comment]
Hrm, no, not fixed. @51b2df00d1f4d8f7ebb8d233a449dfa92eed91b2 reduced the errors for 6 to 3. :-/

Do your worst @chochos...

**Comment by chochos** [comment]
And this `Java()` call is a Java method? or just an illegal declaration?

**Comment by gavinking** [comment]
A java class.

**Comment by quintesse** [comment]
I'm making good progress with this in the typechecker, so if you don't mind I'll take this off your hands and make the necessary changes in the JS backend as well, is that ok with you @chochos ?

**Comment by quintesse** [comment]
I think this can be closed now.

**Comment by gavinking** [comment]
Agreed. Thanks!

**Comment by chochos** [comment]
Cool!

**Comment by quintesse** [comment]
Reopening this again because my changes for ceylon/ceylon-spec#1423 has made this reappear. Not sure how it could happen though, setting a breakpoint clearly shows each error is only added once.

**Comment by FroMage** [comment]
@quintesse are you working on this?

**Comment by quintesse** [comment]
Well, it's right at the top of my list, but I'll probably need some help from @davidfestal (I think it has become an IDE issue, or at least it only appears there)

**Comment by quintesse** [comment]
So this was actually the "fault" of the JVM backend: in the IDE JS is compiled first, which adds its errors to the tree and then when the JVM compiler is finished its reports all errors it encounters in the tree that way duplicating the JS ones (why 3x? Dunno, but it's fixed so I don't care why right now ^^)
So now in the error reporting we ignore errors added by the JS backend (luckily I added that info to the error messages some time ago)
