### ISSUE TITLE
JS model loader does not persist Function.declaredVoid

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-js#640]
I _think_ that the model loader for JS does not persist `declaredVoid`.

**Comment by FroMage** [comment]
How do you notice this?

**Comment by gavinking** [comment]
@FroMage rendering docs in the web runner ;)

**Comment by chochos** [comment]
I'm certain I'm not persisting that, I thought it was calculated at compile time (I suppose it is for source files, but I didn't know it had to be persisted).

**Comment by chochos** [comment]
What about these other flags I'm seeing now? Deferred, anonymous? I'm already persisting anonymous but I'm thinking perhaps I should just store those flags directly instead of several boolean props.
