### ISSUE TITLE
runtime error on "trybeta" example

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-js#645]
1. Go to http://trybeta.ceylon-lang.org
2. Load "Classes and functions 2"
3. Wrap entire example in a function `void runit() { ... }`, and add `runit();` at the end.
4. Click run

output:
```
f1(1.0, 7.0) = 4.0
doubleAvg(1.0, 7.0) = 8.0
Should be the same: 8.0
squareAvg(1.0, 7.0) = 25.0
squareAvg2(1.0, 7.0) = 25.0
Product 'Giraffe, extra long'
Runtime error:
--- TypeError: undefined is not an object (evaluating 'inner$Outer$.outer$.$4w.call')
```

**Comment by jvasileff** [comment]
Oh, forget the `runit()` wrapper. Just run the example as is.

**Comment by quintesse** [comment]
This is a problem for the JS backend, you should be able to reproduce in the IDE or with the CLI  this by wrapping all of that inside yet another function called `run()`.

**Comment by FroMage** [comment]
Minimal test seems to be:

```ceylon
void test(){
class Outer() {
 
    shared class Inner() {
        shared void f() {
			interface I {}
  
            object obj satisfies I {}
        }
    }
}
Outer o = Outer();
Outer.Inner i = o.Inner();
i.f();
print("OK");
}
```

If I remove `obj` or `I` or any of the container classes it works.

**Comment by chochos** [comment]
I'm on it

**Comment by FroMage** [comment]
Excellent!

**Comment by chochos** [comment]
The initialization code for `obj` considers `I` a member or `Inner`, which it is clearly not.
