### ISSUE TITLE
Stitched native declarations don't get properly exported

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-js#646]
At least that's what I think is the problem.
Running the following code fails with a message saying `run` doesn't exist:

**run.ceylon**:

```ceylon
native
shared void run();

native("jvm")
shared void run() {
}
```

**run.js**:

```javascript
function run() {
    console.log("Who am I?");
}
```

The `run.js` file gets stitched in properly I can see it in the output file, but it just doesn't get mentioned in the exports (if I add a `native("js")` section instead of using stitching everything works just fine)

**Comment by FroMage** [comment]
AFAICT exporting native code has to be done by hand. Something like `ex$.run = run;` after your function.

**Comment by FroMage** [comment]
See `numbers.js` in the language module for example: `ex$.JSNumber=JSNumber;`

**Comment by FroMage** [comment]
So I believe with stitching and native JS this has to be done by hand.

**Comment by quintesse** [comment]
Then that should at least be documented: https://github.com/ceylon/ceylon-js/wiki/Native-Compilation

**Comment by FroMage** [comment]
It's a Wiki, be my guest ;)

**Comment by quintesse** [comment]
I'm not the one that knows how this works ;)

**Comment by FroMage** [comment]
Well, let's ask @chochos if the current behaviour is right, or if it's even possible/desirable for the stitcher to generate the exporting itself.
