### ISSUE TITLE
bad arguments for "overloaded" Callable

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-js#651]
This is basically https://github.com/ceylon/ceylon.language/issues/359:

```ceylon
function g([Float]|[] args) {
    switch (args)
    case (is [Float]) {
        return args[0];
    }
    case (is []) {
        return 1.0;
    }
}

Callable<Float,[Float]|[]> f = flatten(g);
print(f(1.0));      // 1.0
print(f());         // <null>
print(f(*[1.0]));   // 1.0
print(f(*[]));      // <null>
```

**Comment by jvasileff** [comment]
I feel like we're taking the wrong approach with Callables/flatten/spread, spending a lot of time troubleshooting many individual cases rather than taking a fresh look at the design.

**Comment by chochos** [comment]
yeah I think I need to reimplement that stuff. For the third time.

**Comment by jvasileff** [comment]
I don't know how well it would translate, but I'd be happy to share ideas from what I did with Dart if you're interested. The simplified explanation is, indicate at the call site if the last argument is a spread argument, and inside the Callable, have an attribute that indicates if the underlying function is variadic, and if so, the index of the variadic (or the # of listed arguments, same idea.) The Callable then has what it needs to re-build the arguments in the form the underlying function requires. For the non-spread & non-variadic case, it's basically a pass-through.

https://github.com/jvasileff/ceylon-dart/blob/fce3f654b51460b676f584b2219a6ea4cba503b0/ceylon-dart-language/source/ceylon/language/module.dart#L1256

Of course, this is *greatly* simplified on Dart right now since it doesn't support reified generics yet.

**Comment by chochos** [comment]
Thanks. I was already working on something similar to what you mention, perhaps not as simple though, but passing more info at the call site does help. I was planning to leave it for 1.3 because it's a major change though...
