### ISSUE TITLE
Native inner classes are not handled correctly in the metamodel

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-js#656]
Currently the test for `Contextual` in the language module fails (it's new, there was no test before).
Turns out that if you create a test project and put the code for `Contextual` and the test in there it compiles and runs just fine. It's only when `Contextual` gets loaded instead of compiled that things fail.
I checked with the debugger and `Contextual` is missing the inner class `Using`.

**Comment by chochos** [comment]
Actually this happens with _any_ internal type you try to use from another module. Model loader's broken once again.
