### ISSUE TITLE
there is no -0 in Ceylon

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-js#669]
The following:

```ceylon
print(1.0/-0);
````

Prints `Infinity` on the JVM, but `-Infinity` on JS. That's wrong, b/c the conversion to `Float` should happen just before the *division*.

**Comment by xkr47** [comment]
Do you mean that -0 is treated as an integer and therefore should be recognized as "0" (because integers in modern computers are using two's complement to represent negative numbers) before it is autoconverted to Float?

**Comment by gavinking** [comment]
Right. Negative zero only exists in the imagination of IEEE floating point arithmetic.

>  to get -Infinity in Ceylon, you should type 1.0/-0.0 ?

Yes.
