### ISSUE TITLE
divide by undefined is zero

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-js#674]
```ceylon
print(-0.0 / (0.0/0.0));
```
prints `-0.0` but should print `NaN`.

**Comment by chochos** [comment]
print NaN, or throw?

**Comment by jvasileff** [comment]
[This](https://en.wikipedia.org/wiki/Division_by_zero#Computer_arithmetic) claims `NaN` for `±0/±0`.

**Comment by chochos** [comment]
on both backends?

**Comment by jvasileff** [comment]
This is already the way it works on the Java backend, and also the JavaScript backend for positive zero.

**Comment by jvasileff** [comment]
Oops, I thought we were commenting on the other issue (divide by 0). Here's a better link: https://en.wikipedia.org/wiki/NaN#Operations_generating_NaN

**Comment by chochos** [comment]
well both issues are closely related
